language: node_js
matrix:
  fast_finish: true
node_js:
- '12'
- '16'
cache:
  yarn: true
  directories:
  - node_modules
script:
- scripts/travis.sh
before_deploy:
- git config --global user.email "npm@cozycloud.cc"
- git config --global user.name "Cozy Bot"
deploy:
- provider: script
  skip-cleanup: true
  script: git checkout master && git remote set-url origin https://cozy-bot:$GITHUB_TOKEN@github.com/konnectors/libs.git
    && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc && yarn lerna
    publish --yes -m "[skip ci] Publish"
  on:
    branch: master
    repo: konnectors/libs
env:
  global:
    #  travis encrypt NPM_TOKEN=<token>
  - secure: Vw4Co+RUhnmv39G7oNT2HSrIJYLJn7ulrFRDxQacbcHKOfOTfSr2UuQuFsYYPMK2zY5d5Zdi/hRHGrHgvg84EmGTqQFRahU+DHs7CS2Hdn88+nEmU0lhl2rlkJ+8xQUPVHFes46uiQGr2j9ORrV63J13ZY9p34vqW9QJjlx/2M46u35mrb9An2mc9JGHEmErnL0Mf55p4OluCi4AaBYnoQ7+Yl+WzL4EGp5OKVWddTuGkag9KHCv/2hyFbFv5dy/kU/50XASZ5KZIY8BYgNxqV3XYSp9by13uv4ZJS73KWX4KXvfqJtIqZBvuSbaIu9XIdUsHcs9X5tm9HbYDTomia7ncYHCzD8kksrZCj4kfB44Oua2Jpx3XTf+n6n67P1kaPcqZyNfYPyK2xivwbAQ9InjZtD2/f4zpK6ziyu/Em5lPwLab4m9kZqvAgIm7EtlpSshzchQG4ds7SEL8ldOiUDFmwkZhvGUDJcwpjhNrF7Zog/Dxl92i8wdvLJxoeB9MO0ElAHiIkBIEcmKQVQ3G7gqIzWs6usJQZ5dzIgEFzvjPuncWdio6p+fLWmxs/DzvEoHn4HgdKcjMeNSG22N7jLlAxel+o0yGTiPpaOBeF/WbID2AHoDB5iJurYM3lOn9x8sMsU0r0Et4gQEU0giKMXu5xcZStxdKmhUK1t3t1M=
    #  travis encrypt GITHUB_TOKEN=<token>
  - secure: TXaWW3Jewmzm76ZVntNos48kMg/IW1VYdjxgJUBcyd2s0l+apHCdP8cRKVyccvsSFWo/dI+4e4C1JEsbrvx1NrRZ59YfKFASXUc71NZrPR2Pd7TuxwUfTYJIo6tapT1tVNfjqnYp0vQXdkz+tJ8k4IsZT/oLx8rIoAXbVJjZ1f6qJW8MQo2vCmisLohm5F6OH7YZPj9hKBq5SMZJZ/zG0sYfh9S2sWos/mdCcLNQKukN2/eXZLjZGpKGm0myL+QPkvvlzNVE9G95JEbSi80WcpAvpM4V6Xi6JDh2WlOGmX4xx4C3nW/4n/ToywpEhA67vbvDZzhlJmo52M0ErOo7fiNunTE8Vob0n+eMGu8jtbmi4xxCcxaUghayk+b+smxLF3PM/rfQVa8vAeIhB6XudF7bECqiQ6P5dn+WPFjYAwJDk005EjFKnKf7yqosH8o3QJd34nmewfQWYVQXi/+NyI0nyr1y+gOmtzW+tauggwtkwMXTSPaJy0ng1/wDXfQk6qAo1JPLALWyFlyK7oXoPrpwt80eFAb80Ln/+S8mho3qXRVIW01484SngMuX4F9ezSXCEcG38zY2J6vEPtQ60MiGGFSJZ99fPAqCggppkxgu6ZSBtBmVgwplw42AEpcy0Wxo61vVmg5bm0dganpgeayqoeIDTpzyl+qULFEbj6A=
